# Generated by Django 4.1.7 on 2023-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("user_name", models.CharField(max_length=50)),
                ("user_password", models.CharField(max_length=50)),
                ("user_position", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
