# Generated by Django 4.1.7 on 2023-05-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_position",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="user",
            table="user2",
        ),
    ]
