# Generated by Django 4.1.7 on 2023-05-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_remove_user_id_alter_user_user_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user3",
        ),
    ]
