# Generated by Django 4.1.7 on 2023-05-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
