# Generated by Django 4.1.7 on 2023-05-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
