# Generated by Django 4.2.6 on 2023-10-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(max_length=255)),
                ('answer_content', models.CharField(max_length=50)),
                ('question_extraction', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'test',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
